import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react"
import { Geist, Geist_Mono } from "next/font/google";
import { App, ConfigProvider } from 'antd';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Navbar from '@/components/layout/Navbar';
import CustContent from '@/components/layout/CustContent';
import jaJP from 'antd/locale/ja_JP';
import "./globals.css";
import '@ant-design/v5-patch-for-react-19';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Antd-Demo",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {

  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <ConfigProvider locale={jaJP} componentSize="small">
            <App>
              <AntdRegistry>
                <Navbar />
                <CustContent>
                  {children}
                </CustContent>
              </AntdRegistry>
            </App>
          </ConfigProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
